TOP=../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

#=============================
# Build an ioc application
# Use PROD_IOC_RTEMS for RTEMS only
# Use PROD_IOC_Linux for Linux only
PROD_IOC = lakeshore335

PROD_SYS_LIBS_DEFAULT += pcre

# lakeshore335.dbd will be created and installed
DBD += lakeshore335.dbd

# lakeshore335.dbd will be made up from these files:
lakeshore335_DBD += base.dbd
lakeshore335_DBD += iocAdmin.dbd
lakeshore335_DBD += autosaveSupport.dbd
lakeshore335_DBD += asyn.dbd
lakeshore335_DBD += asynRecord.dbd
lakeshore335_DBD += stream.dbd
lakeshore335_DBD += drvAsynIPPort.dbd
lakeshore335_DBD += drvAsynSerialPort.dbd

# <name>_registerRecordDeviceDriver.cpp will be created from <name>.dbd
lakeshore335_SRCS += lakeshore335_registerRecordDeviceDriver.cpp
lakeshore335_SRCS_DEFAULT += lakeshore335Main.cpp

# Add locally compiled object code
#lakeshore335_SRCS += dbSubExample.c

lakeshore335_LIBS += devIocStats
lakeshore335_LIBS += autosave
lakeshore335_LIBS += asyn
lakeshore335_LIBS += stream
lakeshore335_LIBS += $(EPICS_BASE_IOC_LIBS)

#===========================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

